### ISSUE TITLE
Zigbee2MqttAssistant: Unable to connect to MQTT server mosquitto

### ISSUE THREAD

**Issue by batamire** [gcgarner/IOTstack#236]
Fresh install, from the logs:

```
Starting Zigbee2MqttAssistant v0.3.157+Branch.master.Sha.ea388c3bbc2d43c4c9c62f27bb6764911ba4acc9...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to connect to MQTT server mosquitto.
MQTTnet.Exceptions.MqttCommunicationException: Name or service not known
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__277_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.ReconnectIfRequiredAsync()
```

Mosquitto had errors too:

```
Error saving in-memory database, unable to open /mosquitto/data/mosquitto.db.new for writing
```

Solved it with `chown -R 777 volumes/mosquitto/*` which feels very wrong...

```
pi@raspberrypi:~/IOTstack $ ls -la volumes/mosquitto/
total 20
drwxr-xr-x  5 root root 4096 Apr  1 18:21 .
drwxr-xr-x 10 pi   pi   4096 Apr  1 18:22 ..
drwxrwxrwx  2 root root 4096 Apr  2 17:14 data
drwxrwxrwx  2 root root 4096 Apr  2 16:53 log
drwxrwxrwx  2 root root 4096 Apr  1 18:21 pwfile
```

**Comment by batamire** [comment]
Just realised the build script wasn't accepting "Y" for `chown -R 1883:1883 ./volumes/mosquitto` so I opened another issue just for this

**Comment by batamire** [comment]
Closing for new repo: [https://github.com/SensorsIot/IOTstack/issues/308](https://github.com/SensorsIot/IOTstack/issues/308)
